
user/_init:     file format elf64-littleriscv


Disassembly of section .text:

0000000000000000 <main>:
// Created by hy on 2021/2/5.
//

#include "user.h"

int main() {
   0:	7175                	addi	sp,sp,-144
   2:	e506                	sd	ra,136(sp)
   4:	e122                	sd	s0,128(sp)
   6:	fca6                	sd	s1,120(sp)
   8:	f8ca                	sd	s2,112(sp)
   a:	0900                	addi	s0,sp,144
    char buf[100];
    int pid = fork();
   c:	00000097          	auipc	ra,0x0
  10:	06a080e7          	jalr	106(ra) # 76 <fork>
  14:	84aa                	mv	s1,a0
    printf("pid=%d\n", pid);
  16:	85aa                	mv	a1,a0
  18:	00000517          	auipc	a0,0x0
  1c:	34850513          	addi	a0,a0,840 # 360 <printf+0x36>
  20:	00000097          	auipc	ra,0x0
  24:	30a080e7          	jalr	778(ra) # 32a <printf>
    read(buf);
  28:	f7840513          	addi	a0,s0,-136
  2c:	00000097          	auipc	ra,0x0
  30:	042080e7          	jalr	66(ra) # 6e <read>
    printf("%s",buf);
  34:	f7840593          	addi	a1,s0,-136
  38:	00000517          	auipc	a0,0x0
  3c:	33050513          	addi	a0,a0,816 # 368 <printf+0x3e>
  40:	00000097          	auipc	ra,0x0
  44:	2ea080e7          	jalr	746(ra) # 32a <printf>
    for(;;)
        printf("pid=%d\n", pid);
  48:	00000917          	auipc	s2,0x0
  4c:	31890913          	addi	s2,s2,792 # 360 <printf+0x36>
  50:	85a6                	mv	a1,s1
  52:	854a                	mv	a0,s2
  54:	00000097          	auipc	ra,0x0
  58:	2d6080e7          	jalr	726(ra) # 32a <printf>
    for(;;)
  5c:	bfd5                	j	50 <main+0x50>

000000000000005e <putchar>:
# generated by usys.pl - do not edit
#include "kernel/trap/syscall.h"
.global putchar
putchar:
 li a7, SYS_putchar
  5e:	4885                	li	a7,1
 ecall
  60:	00000073          	ecall
 ret
  64:	8082                	ret

0000000000000066 <exec>:
.global exec
exec:
 li a7, SYS_exec
  66:	4889                	li	a7,2
 ecall
  68:	00000073          	ecall
 ret
  6c:	8082                	ret

000000000000006e <read>:
.global read
read:
 li a7, SYS_read
  6e:	4891                	li	a7,4
 ecall
  70:	00000073          	ecall
 ret
  74:	8082                	ret

0000000000000076 <fork>:
.global fork
fork:
 li a7, SYS_fork
  76:	4895                	li	a7,5
 ecall
  78:	00000073          	ecall
 ret
  7c:	8082                	ret

000000000000007e <exit>:
.global exit
exit:
 li a7, SYS_exit
  7e:	488d                	li	a7,3
 ecall
  80:	00000073          	ecall
 ret
  84:	8082                	ret

0000000000000086 <printint>:
    putchar(c);
}

static void
printint(int fd, int xx, int base, int sgn)
{
  86:	7179                	addi	sp,sp,-48
  88:	f406                	sd	ra,40(sp)
  8a:	f022                	sd	s0,32(sp)
  8c:	ec26                	sd	s1,24(sp)
  8e:	e84a                	sd	s2,16(sp)
  90:	1800                	addi	s0,sp,48
    char buf[16];
    int i, neg;
    uint x;

    neg = 0;
    if(sgn && xx < 0){
  92:	c299                	beqz	a3,98 <printint+0x12>
  94:	0805c663          	bltz	a1,120 <printint+0x9a>
        neg = 1;
        x = -xx;
    } else {
        x = xx;
  98:	2581                	sext.w	a1,a1
    neg = 0;
  9a:	4881                	li	a7,0
  9c:	fd040693          	addi	a3,s0,-48
    }

    i = 0;
  a0:	4701                	li	a4,0
    do{
        buf[i++] = digits[x % base];
  a2:	2601                	sext.w	a2,a2
  a4:	00000517          	auipc	a0,0x0
  a8:	2d450513          	addi	a0,a0,724 # 378 <digits>
  ac:	883a                	mv	a6,a4
  ae:	2705                	addiw	a4,a4,1
  b0:	02c5f7bb          	remuw	a5,a1,a2
  b4:	1782                	slli	a5,a5,0x20
  b6:	9381                	srli	a5,a5,0x20
  b8:	97aa                	add	a5,a5,a0
  ba:	0007c783          	lbu	a5,0(a5)
  be:	00f68023          	sb	a5,0(a3)
    }while((x /= base) != 0);
  c2:	0005879b          	sext.w	a5,a1
  c6:	02c5d5bb          	divuw	a1,a1,a2
  ca:	0685                	addi	a3,a3,1
  cc:	fec7f0e3          	bgeu	a5,a2,ac <printint+0x26>
    if(neg)
  d0:	00088b63          	beqz	a7,e6 <printint+0x60>
        buf[i++] = '-';
  d4:	fe040793          	addi	a5,s0,-32
  d8:	973e                	add	a4,a4,a5
  da:	02d00793          	li	a5,45
  de:	fef70823          	sb	a5,-16(a4)
  e2:	0028071b          	addiw	a4,a6,2

    while(--i >= 0)
  e6:	02e05763          	blez	a4,114 <printint+0x8e>
  ea:	fd040793          	addi	a5,s0,-48
  ee:	00e784b3          	add	s1,a5,a4
  f2:	fff78913          	addi	s2,a5,-1
  f6:	993a                	add	s2,s2,a4
  f8:	377d                	addiw	a4,a4,-1
  fa:	1702                	slli	a4,a4,0x20
  fc:	9301                	srli	a4,a4,0x20
  fe:	40e90933          	sub	s2,s2,a4
    putchar(c);
 102:	fff4c503          	lbu	a0,-1(s1)
 106:	00000097          	auipc	ra,0x0
 10a:	f58080e7          	jalr	-168(ra) # 5e <putchar>
    while(--i >= 0)
 10e:	14fd                	addi	s1,s1,-1
 110:	ff2499e3          	bne	s1,s2,102 <printint+0x7c>
        putc(fd, buf[i]);
}
 114:	70a2                	ld	ra,40(sp)
 116:	7402                	ld	s0,32(sp)
 118:	64e2                	ld	s1,24(sp)
 11a:	6942                	ld	s2,16(sp)
 11c:	6145                	addi	sp,sp,48
 11e:	8082                	ret
        x = -xx;
 120:	40b005bb          	negw	a1,a1
        neg = 1;
 124:	4885                	li	a7,1
        x = -xx;
 126:	bf9d                	j	9c <printint+0x16>

0000000000000128 <vprintf>:
}

// Print to the given fd. Only understands %d, %x, %p, %s.
void
vprintf(int fd, const char *fmt, va_list ap)
{
 128:	7119                	addi	sp,sp,-128
 12a:	fc86                	sd	ra,120(sp)
 12c:	f8a2                	sd	s0,112(sp)
 12e:	f4a6                	sd	s1,104(sp)
 130:	f0ca                	sd	s2,96(sp)
 132:	ecce                	sd	s3,88(sp)
 134:	e8d2                	sd	s4,80(sp)
 136:	e4d6                	sd	s5,72(sp)
 138:	e0da                	sd	s6,64(sp)
 13a:	fc5e                	sd	s7,56(sp)
 13c:	f862                	sd	s8,48(sp)
 13e:	f466                	sd	s9,40(sp)
 140:	f06a                	sd	s10,32(sp)
 142:	ec6e                	sd	s11,24(sp)
 144:	0100                	addi	s0,sp,128
 146:	f8a43423          	sd	a0,-120(s0)
    char *s;
    int c, i, state;

    state = 0;
    for(i = 0; fmt[i]; i++){
 14a:	0005c903          	lbu	s2,0(a1)
 14e:	18090863          	beqz	s2,2de <vprintf+0x1b6>
 152:	8ab2                	mv	s5,a2
 154:	00158493          	addi	s1,a1,1
    state = 0;
 158:	4981                	li	s3,0
            if(c == '%'){
                state = '%';
            } else {
                putc(fd, c);
            }
        } else if(state == '%'){
 15a:	02500a13          	li	s4,37
            if(c == 'd'){
 15e:	06400b93          	li	s7,100
                printint(fd, va_arg(ap, int), 10, 1);
            } else if(c == 'l') {
 162:	06c00c13          	li	s8,108
                printint(fd, va_arg(ap, uint64), 10, 0);
            } else if(c == 'x') {
 166:	07800c93          	li	s9,120
                printint(fd, va_arg(ap, int), 16, 0);
            } else if(c == 'p') {
 16a:	07000d13          	li	s10,112
                printptr(fd, va_arg(ap, uint64));
            } else if(c == 's'){
 16e:	07300d93          	li	s11,115
        putc(fd, digits[x >> (sizeof(uint64) * 8 - 4)]);
 172:	00000b17          	auipc	s6,0x0
 176:	206b0b13          	addi	s6,s6,518 # 378 <digits>
 17a:	a831                	j	196 <vprintf+0x6e>
    putchar(c);
 17c:	854a                	mv	a0,s2
 17e:	00000097          	auipc	ra,0x0
 182:	ee0080e7          	jalr	-288(ra) # 5e <putchar>
}
 186:	a019                	j	18c <vprintf+0x64>
        } else if(state == '%'){
 188:	01498f63          	beq	s3,s4,1a6 <vprintf+0x7e>
    for(i = 0; fmt[i]; i++){
 18c:	0485                	addi	s1,s1,1
 18e:	fff4c903          	lbu	s2,-1(s1)
 192:	14090663          	beqz	s2,2de <vprintf+0x1b6>
        c = fmt[i] & 0xff;
 196:	0009079b          	sext.w	a5,s2
        if(state == 0){
 19a:	fe0997e3          	bnez	s3,188 <vprintf+0x60>
            if(c == '%'){
 19e:	fd479fe3          	bne	a5,s4,17c <vprintf+0x54>
                state = '%';
 1a2:	89be                	mv	s3,a5
 1a4:	b7e5                	j	18c <vprintf+0x64>
            if(c == 'd'){
 1a6:	03778c63          	beq	a5,s7,1de <vprintf+0xb6>
            } else if(c == 'l') {
 1aa:	05878963          	beq	a5,s8,1fc <vprintf+0xd4>
            } else if(c == 'x') {
 1ae:	07978663          	beq	a5,s9,21a <vprintf+0xf2>
            } else if(c == 'p') {
 1b2:	09a78363          	beq	a5,s10,238 <vprintf+0x110>
            } else if(c == 's'){
 1b6:	0db78463          	beq	a5,s11,27e <vprintf+0x156>
                    s = "(null)";
                while(*s != 0){
                    putc(fd, *s);
                    s++;
                }
            } else if(c == 'c'){
 1ba:	06300713          	li	a4,99
 1be:	0ee78b63          	beq	a5,a4,2b4 <vprintf+0x18c>
                putc(fd, va_arg(ap, uint));
            } else if(c == '%'){
 1c2:	11478463          	beq	a5,s4,2ca <vprintf+0x1a2>
    putchar(c);
 1c6:	8552                	mv	a0,s4
 1c8:	00000097          	auipc	ra,0x0
 1cc:	e96080e7          	jalr	-362(ra) # 5e <putchar>
 1d0:	854a                	mv	a0,s2
 1d2:	00000097          	auipc	ra,0x0
 1d6:	e8c080e7          	jalr	-372(ra) # 5e <putchar>
            } else {
                // Unknown % sequence.  Print it to draw attention.
                putc(fd, '%');
                putc(fd, c);
            }
            state = 0;
 1da:	4981                	li	s3,0
}
 1dc:	bf45                	j	18c <vprintf+0x64>
                printint(fd, va_arg(ap, int), 10, 1);
 1de:	008a8913          	addi	s2,s5,8
 1e2:	4685                	li	a3,1
 1e4:	4629                	li	a2,10
 1e6:	000aa583          	lw	a1,0(s5)
 1ea:	f8843503          	ld	a0,-120(s0)
 1ee:	00000097          	auipc	ra,0x0
 1f2:	e98080e7          	jalr	-360(ra) # 86 <printint>
 1f6:	8aca                	mv	s5,s2
            state = 0;
 1f8:	4981                	li	s3,0
 1fa:	bf49                	j	18c <vprintf+0x64>
                printint(fd, va_arg(ap, uint64), 10, 0);
 1fc:	008a8913          	addi	s2,s5,8
 200:	4681                	li	a3,0
 202:	4629                	li	a2,10
 204:	000aa583          	lw	a1,0(s5)
 208:	f8843503          	ld	a0,-120(s0)
 20c:	00000097          	auipc	ra,0x0
 210:	e7a080e7          	jalr	-390(ra) # 86 <printint>
 214:	8aca                	mv	s5,s2
            state = 0;
 216:	4981                	li	s3,0
 218:	bf95                	j	18c <vprintf+0x64>
                printint(fd, va_arg(ap, int), 16, 0);
 21a:	008a8913          	addi	s2,s5,8
 21e:	4681                	li	a3,0
 220:	4641                	li	a2,16
 222:	000aa583          	lw	a1,0(s5)
 226:	f8843503          	ld	a0,-120(s0)
 22a:	00000097          	auipc	ra,0x0
 22e:	e5c080e7          	jalr	-420(ra) # 86 <printint>
 232:	8aca                	mv	s5,s2
            state = 0;
 234:	4981                	li	s3,0
 236:	bf99                	j	18c <vprintf+0x64>
                printptr(fd, va_arg(ap, uint64));
 238:	008a8793          	addi	a5,s5,8
 23c:	f8f43023          	sd	a5,-128(s0)
 240:	000ab983          	ld	s3,0(s5)
    putchar(c);
 244:	03000513          	li	a0,48
 248:	00000097          	auipc	ra,0x0
 24c:	e16080e7          	jalr	-490(ra) # 5e <putchar>
 250:	8566                	mv	a0,s9
 252:	00000097          	auipc	ra,0x0
 256:	e0c080e7          	jalr	-500(ra) # 5e <putchar>
 25a:	4941                	li	s2,16
        putc(fd, digits[x >> (sizeof(uint64) * 8 - 4)]);
 25c:	03c9d793          	srli	a5,s3,0x3c
 260:	97da                	add	a5,a5,s6
    putchar(c);
 262:	0007c503          	lbu	a0,0(a5)
 266:	00000097          	auipc	ra,0x0
 26a:	df8080e7          	jalr	-520(ra) # 5e <putchar>
    for (i = 0; i < (sizeof(uint64) * 2); i++, x <<= 4)
 26e:	0992                	slli	s3,s3,0x4
 270:	397d                	addiw	s2,s2,-1
 272:	fe0915e3          	bnez	s2,25c <vprintf+0x134>
                printptr(fd, va_arg(ap, uint64));
 276:	f8043a83          	ld	s5,-128(s0)
            state = 0;
 27a:	4981                	li	s3,0
 27c:	bf01                	j	18c <vprintf+0x64>
                s = va_arg(ap, char*);
 27e:	008a8993          	addi	s3,s5,8
 282:	000ab903          	ld	s2,0(s5)
                if(s == 0)
 286:	02090063          	beqz	s2,2a6 <vprintf+0x17e>
                while(*s != 0){
 28a:	00094503          	lbu	a0,0(s2)
 28e:	c529                	beqz	a0,2d8 <vprintf+0x1b0>
    putchar(c);
 290:	00000097          	auipc	ra,0x0
 294:	dce080e7          	jalr	-562(ra) # 5e <putchar>
                    s++;
 298:	0905                	addi	s2,s2,1
                while(*s != 0){
 29a:	00094503          	lbu	a0,0(s2)
 29e:	f96d                	bnez	a0,290 <vprintf+0x168>
                s = va_arg(ap, char*);
 2a0:	8ace                	mv	s5,s3
            state = 0;
 2a2:	4981                	li	s3,0
 2a4:	b5e5                	j	18c <vprintf+0x64>
                    s = "(null)";
 2a6:	00000917          	auipc	s2,0x0
 2aa:	0ca90913          	addi	s2,s2,202 # 370 <printf+0x46>
                while(*s != 0){
 2ae:	02800513          	li	a0,40
 2b2:	bff9                	j	290 <vprintf+0x168>
                putc(fd, va_arg(ap, uint));
 2b4:	008a8913          	addi	s2,s5,8
    putchar(c);
 2b8:	000ac503          	lbu	a0,0(s5)
 2bc:	00000097          	auipc	ra,0x0
 2c0:	da2080e7          	jalr	-606(ra) # 5e <putchar>
                putc(fd, va_arg(ap, uint));
 2c4:	8aca                	mv	s5,s2
            state = 0;
 2c6:	4981                	li	s3,0
}
 2c8:	b5d1                	j	18c <vprintf+0x64>
    putchar(c);
 2ca:	8552                	mv	a0,s4
 2cc:	00000097          	auipc	ra,0x0
 2d0:	d92080e7          	jalr	-622(ra) # 5e <putchar>
            state = 0;
 2d4:	4981                	li	s3,0
}
 2d6:	bd5d                	j	18c <vprintf+0x64>
                s = va_arg(ap, char*);
 2d8:	8ace                	mv	s5,s3
            state = 0;
 2da:	4981                	li	s3,0
 2dc:	bd45                	j	18c <vprintf+0x64>
        }
    }
}
 2de:	70e6                	ld	ra,120(sp)
 2e0:	7446                	ld	s0,112(sp)
 2e2:	74a6                	ld	s1,104(sp)
 2e4:	7906                	ld	s2,96(sp)
 2e6:	69e6                	ld	s3,88(sp)
 2e8:	6a46                	ld	s4,80(sp)
 2ea:	6aa6                	ld	s5,72(sp)
 2ec:	6b06                	ld	s6,64(sp)
 2ee:	7be2                	ld	s7,56(sp)
 2f0:	7c42                	ld	s8,48(sp)
 2f2:	7ca2                	ld	s9,40(sp)
 2f4:	7d02                	ld	s10,32(sp)
 2f6:	6de2                	ld	s11,24(sp)
 2f8:	6109                	addi	sp,sp,128
 2fa:	8082                	ret

00000000000002fc <fprintf>:

void
fprintf(int fd, const char *fmt, ...)
{
 2fc:	715d                	addi	sp,sp,-80
 2fe:	ec06                	sd	ra,24(sp)
 300:	e822                	sd	s0,16(sp)
 302:	1000                	addi	s0,sp,32
 304:	e010                	sd	a2,0(s0)
 306:	e414                	sd	a3,8(s0)
 308:	e818                	sd	a4,16(s0)
 30a:	ec1c                	sd	a5,24(s0)
 30c:	03043023          	sd	a6,32(s0)
 310:	03143423          	sd	a7,40(s0)
    va_list ap;

    va_start(ap, fmt);
 314:	fe843423          	sd	s0,-24(s0)
    vprintf(fd, fmt, ap);
 318:	8622                	mv	a2,s0
 31a:	00000097          	auipc	ra,0x0
 31e:	e0e080e7          	jalr	-498(ra) # 128 <vprintf>
}
 322:	60e2                	ld	ra,24(sp)
 324:	6442                	ld	s0,16(sp)
 326:	6161                	addi	sp,sp,80
 328:	8082                	ret

000000000000032a <printf>:

void
printf(const char *fmt, ...)
{
 32a:	711d                	addi	sp,sp,-96
 32c:	ec06                	sd	ra,24(sp)
 32e:	e822                	sd	s0,16(sp)
 330:	1000                	addi	s0,sp,32
 332:	e40c                	sd	a1,8(s0)
 334:	e810                	sd	a2,16(s0)
 336:	ec14                	sd	a3,24(s0)
 338:	f018                	sd	a4,32(s0)
 33a:	f41c                	sd	a5,40(s0)
 33c:	03043823          	sd	a6,48(s0)
 340:	03143c23          	sd	a7,56(s0)
    va_list ap;

    va_start(ap, fmt);
 344:	00840613          	addi	a2,s0,8
 348:	fec43423          	sd	a2,-24(s0)
    vprintf(1, fmt, ap);
 34c:	85aa                	mv	a1,a0
 34e:	4505                	li	a0,1
 350:	00000097          	auipc	ra,0x0
 354:	dd8080e7          	jalr	-552(ra) # 128 <vprintf>
}
 358:	60e2                	ld	ra,24(sp)
 35a:	6442                	ld	s0,16(sp)
 35c:	6125                	addi	sp,sp,96
 35e:	8082                	ret
