
user/_init:     file format elf64-littleriscv


Disassembly of section .text:

0000000000000000 <main>:
// Created by hy on 2021/2/5.
//

#include "user.h"

int main() {
   0:	1141                	addi	sp,sp,-16
   2:	e406                	sd	ra,8(sp)
   4:	e022                	sd	s0,0(sp)
   6:	0800                	addi	s0,sp,16
    char *s = "world!";
//    char str[100];
//    read(str);
    printf("hello %s", s);
   8:	00000597          	auipc	a1,0x0
   c:	31858593          	addi	a1,a1,792 # 320 <printf+0x3a>
  10:	00000517          	auipc	a0,0x0
  14:	31850513          	addi	a0,a0,792 # 328 <printf+0x42>
  18:	00000097          	auipc	ra,0x0
  1c:	2ce080e7          	jalr	718(ra) # 2e6 <printf>
    return 0;
}
  20:	4501                	li	a0,0
  22:	60a2                	ld	ra,8(sp)
  24:	6402                	ld	s0,0(sp)
  26:	0141                	addi	sp,sp,16
  28:	8082                	ret

000000000000002a <putchar>:
# generated by usys.pl - do not edit
#include "kernel/trap/syscall.h"
.global putchar
putchar:
 li a7, SYS_putchar
  2a:	4885                	li	a7,1
 ecall
  2c:	00000073          	ecall
 ret
  30:	8082                	ret

0000000000000032 <exec>:
.global exec
exec:
 li a7, SYS_exec
  32:	4889                	li	a7,2
 ecall
  34:	00000073          	ecall
 ret
  38:	8082                	ret

000000000000003a <read>:
.global read
read:
 li a7, SYS_read
  3a:	4891                	li	a7,4
 ecall
  3c:	00000073          	ecall
 ret
  40:	8082                	ret

0000000000000042 <printint>:
    putchar(c);
}

static void
printint(int fd, int xx, int base, int sgn)
{
  42:	7179                	addi	sp,sp,-48
  44:	f406                	sd	ra,40(sp)
  46:	f022                	sd	s0,32(sp)
  48:	ec26                	sd	s1,24(sp)
  4a:	e84a                	sd	s2,16(sp)
  4c:	1800                	addi	s0,sp,48
    char buf[16];
    int i, neg;
    uint x;

    neg = 0;
    if(sgn && xx < 0){
  4e:	c299                	beqz	a3,54 <printint+0x12>
  50:	0805c663          	bltz	a1,dc <printint+0x9a>
        neg = 1;
        x = -xx;
    } else {
        x = xx;
  54:	2581                	sext.w	a1,a1
    neg = 0;
  56:	4881                	li	a7,0
  58:	fd040693          	addi	a3,s0,-48
    }

    i = 0;
  5c:	4701                	li	a4,0
    do{
        buf[i++] = digits[x % base];
  5e:	2601                	sext.w	a2,a2
  60:	00000517          	auipc	a0,0x0
  64:	2e050513          	addi	a0,a0,736 # 340 <digits>
  68:	883a                	mv	a6,a4
  6a:	2705                	addiw	a4,a4,1
  6c:	02c5f7bb          	remuw	a5,a1,a2
  70:	1782                	slli	a5,a5,0x20
  72:	9381                	srli	a5,a5,0x20
  74:	97aa                	add	a5,a5,a0
  76:	0007c783          	lbu	a5,0(a5)
  7a:	00f68023          	sb	a5,0(a3)
    }while((x /= base) != 0);
  7e:	0005879b          	sext.w	a5,a1
  82:	02c5d5bb          	divuw	a1,a1,a2
  86:	0685                	addi	a3,a3,1
  88:	fec7f0e3          	bgeu	a5,a2,68 <printint+0x26>
    if(neg)
  8c:	00088b63          	beqz	a7,a2 <printint+0x60>
        buf[i++] = '-';
  90:	fe040793          	addi	a5,s0,-32
  94:	973e                	add	a4,a4,a5
  96:	02d00793          	li	a5,45
  9a:	fef70823          	sb	a5,-16(a4)
  9e:	0028071b          	addiw	a4,a6,2

    while(--i >= 0)
  a2:	02e05763          	blez	a4,d0 <printint+0x8e>
  a6:	fd040793          	addi	a5,s0,-48
  aa:	00e784b3          	add	s1,a5,a4
  ae:	fff78913          	addi	s2,a5,-1
  b2:	993a                	add	s2,s2,a4
  b4:	377d                	addiw	a4,a4,-1
  b6:	1702                	slli	a4,a4,0x20
  b8:	9301                	srli	a4,a4,0x20
  ba:	40e90933          	sub	s2,s2,a4
    putchar(c);
  be:	fff4c503          	lbu	a0,-1(s1)
  c2:	00000097          	auipc	ra,0x0
  c6:	f68080e7          	jalr	-152(ra) # 2a <putchar>
    while(--i >= 0)
  ca:	14fd                	addi	s1,s1,-1
  cc:	ff2499e3          	bne	s1,s2,be <printint+0x7c>
        putc(fd, buf[i]);
}
  d0:	70a2                	ld	ra,40(sp)
  d2:	7402                	ld	s0,32(sp)
  d4:	64e2                	ld	s1,24(sp)
  d6:	6942                	ld	s2,16(sp)
  d8:	6145                	addi	sp,sp,48
  da:	8082                	ret
        x = -xx;
  dc:	40b005bb          	negw	a1,a1
        neg = 1;
  e0:	4885                	li	a7,1
        x = -xx;
  e2:	bf9d                	j	58 <printint+0x16>

00000000000000e4 <vprintf>:
}

// Print to the given fd. Only understands %d, %x, %p, %s.
void
vprintf(int fd, const char *fmt, va_list ap)
{
  e4:	7119                	addi	sp,sp,-128
  e6:	fc86                	sd	ra,120(sp)
  e8:	f8a2                	sd	s0,112(sp)
  ea:	f4a6                	sd	s1,104(sp)
  ec:	f0ca                	sd	s2,96(sp)
  ee:	ecce                	sd	s3,88(sp)
  f0:	e8d2                	sd	s4,80(sp)
  f2:	e4d6                	sd	s5,72(sp)
  f4:	e0da                	sd	s6,64(sp)
  f6:	fc5e                	sd	s7,56(sp)
  f8:	f862                	sd	s8,48(sp)
  fa:	f466                	sd	s9,40(sp)
  fc:	f06a                	sd	s10,32(sp)
  fe:	ec6e                	sd	s11,24(sp)
 100:	0100                	addi	s0,sp,128
 102:	f8a43423          	sd	a0,-120(s0)
    char *s;
    int c, i, state;

    state = 0;
    for(i = 0; fmt[i]; i++){
 106:	0005c903          	lbu	s2,0(a1)
 10a:	18090863          	beqz	s2,29a <vprintf+0x1b6>
 10e:	8ab2                	mv	s5,a2
 110:	00158493          	addi	s1,a1,1
    state = 0;
 114:	4981                	li	s3,0
            if(c == '%'){
                state = '%';
            } else {
                putc(fd, c);
            }
        } else if(state == '%'){
 116:	02500a13          	li	s4,37
            if(c == 'd'){
 11a:	06400b93          	li	s7,100
                printint(fd, va_arg(ap, int), 10, 1);
            } else if(c == 'l') {
 11e:	06c00c13          	li	s8,108
                printint(fd, va_arg(ap, uint64), 10, 0);
            } else if(c == 'x') {
 122:	07800c93          	li	s9,120
                printint(fd, va_arg(ap, int), 16, 0);
            } else if(c == 'p') {
 126:	07000d13          	li	s10,112
                printptr(fd, va_arg(ap, uint64));
            } else if(c == 's'){
 12a:	07300d93          	li	s11,115
        putc(fd, digits[x >> (sizeof(uint64) * 8 - 4)]);
 12e:	00000b17          	auipc	s6,0x0
 132:	212b0b13          	addi	s6,s6,530 # 340 <digits>
 136:	a831                	j	152 <vprintf+0x6e>
    putchar(c);
 138:	854a                	mv	a0,s2
 13a:	00000097          	auipc	ra,0x0
 13e:	ef0080e7          	jalr	-272(ra) # 2a <putchar>
}
 142:	a019                	j	148 <vprintf+0x64>
        } else if(state == '%'){
 144:	01498f63          	beq	s3,s4,162 <vprintf+0x7e>
    for(i = 0; fmt[i]; i++){
 148:	0485                	addi	s1,s1,1
 14a:	fff4c903          	lbu	s2,-1(s1)
 14e:	14090663          	beqz	s2,29a <vprintf+0x1b6>
        c = fmt[i] & 0xff;
 152:	0009079b          	sext.w	a5,s2
        if(state == 0){
 156:	fe0997e3          	bnez	s3,144 <vprintf+0x60>
            if(c == '%'){
 15a:	fd479fe3          	bne	a5,s4,138 <vprintf+0x54>
                state = '%';
 15e:	89be                	mv	s3,a5
 160:	b7e5                	j	148 <vprintf+0x64>
            if(c == 'd'){
 162:	03778c63          	beq	a5,s7,19a <vprintf+0xb6>
            } else if(c == 'l') {
 166:	05878963          	beq	a5,s8,1b8 <vprintf+0xd4>
            } else if(c == 'x') {
 16a:	07978663          	beq	a5,s9,1d6 <vprintf+0xf2>
            } else if(c == 'p') {
 16e:	09a78363          	beq	a5,s10,1f4 <vprintf+0x110>
            } else if(c == 's'){
 172:	0db78463          	beq	a5,s11,23a <vprintf+0x156>
                    s = "(null)";
                while(*s != 0){
                    putc(fd, *s);
                    s++;
                }
            } else if(c == 'c'){
 176:	06300713          	li	a4,99
 17a:	0ee78b63          	beq	a5,a4,270 <vprintf+0x18c>
                putc(fd, va_arg(ap, uint));
            } else if(c == '%'){
 17e:	11478463          	beq	a5,s4,286 <vprintf+0x1a2>
    putchar(c);
 182:	8552                	mv	a0,s4
 184:	00000097          	auipc	ra,0x0
 188:	ea6080e7          	jalr	-346(ra) # 2a <putchar>
 18c:	854a                	mv	a0,s2
 18e:	00000097          	auipc	ra,0x0
 192:	e9c080e7          	jalr	-356(ra) # 2a <putchar>
            } else {
                // Unknown % sequence.  Print it to draw attention.
                putc(fd, '%');
                putc(fd, c);
            }
            state = 0;
 196:	4981                	li	s3,0
}
 198:	bf45                	j	148 <vprintf+0x64>
                printint(fd, va_arg(ap, int), 10, 1);
 19a:	008a8913          	addi	s2,s5,8
 19e:	4685                	li	a3,1
 1a0:	4629                	li	a2,10
 1a2:	000aa583          	lw	a1,0(s5)
 1a6:	f8843503          	ld	a0,-120(s0)
 1aa:	00000097          	auipc	ra,0x0
 1ae:	e98080e7          	jalr	-360(ra) # 42 <printint>
 1b2:	8aca                	mv	s5,s2
            state = 0;
 1b4:	4981                	li	s3,0
 1b6:	bf49                	j	148 <vprintf+0x64>
                printint(fd, va_arg(ap, uint64), 10, 0);
 1b8:	008a8913          	addi	s2,s5,8
 1bc:	4681                	li	a3,0
 1be:	4629                	li	a2,10
 1c0:	000aa583          	lw	a1,0(s5)
 1c4:	f8843503          	ld	a0,-120(s0)
 1c8:	00000097          	auipc	ra,0x0
 1cc:	e7a080e7          	jalr	-390(ra) # 42 <printint>
 1d0:	8aca                	mv	s5,s2
            state = 0;
 1d2:	4981                	li	s3,0
 1d4:	bf95                	j	148 <vprintf+0x64>
                printint(fd, va_arg(ap, int), 16, 0);
 1d6:	008a8913          	addi	s2,s5,8
 1da:	4681                	li	a3,0
 1dc:	4641                	li	a2,16
 1de:	000aa583          	lw	a1,0(s5)
 1e2:	f8843503          	ld	a0,-120(s0)
 1e6:	00000097          	auipc	ra,0x0
 1ea:	e5c080e7          	jalr	-420(ra) # 42 <printint>
 1ee:	8aca                	mv	s5,s2
            state = 0;
 1f0:	4981                	li	s3,0
 1f2:	bf99                	j	148 <vprintf+0x64>
                printptr(fd, va_arg(ap, uint64));
 1f4:	008a8793          	addi	a5,s5,8
 1f8:	f8f43023          	sd	a5,-128(s0)
 1fc:	000ab983          	ld	s3,0(s5)
    putchar(c);
 200:	03000513          	li	a0,48
 204:	00000097          	auipc	ra,0x0
 208:	e26080e7          	jalr	-474(ra) # 2a <putchar>
 20c:	8566                	mv	a0,s9
 20e:	00000097          	auipc	ra,0x0
 212:	e1c080e7          	jalr	-484(ra) # 2a <putchar>
 216:	4941                	li	s2,16
        putc(fd, digits[x >> (sizeof(uint64) * 8 - 4)]);
 218:	03c9d793          	srli	a5,s3,0x3c
 21c:	97da                	add	a5,a5,s6
    putchar(c);
 21e:	0007c503          	lbu	a0,0(a5)
 222:	00000097          	auipc	ra,0x0
 226:	e08080e7          	jalr	-504(ra) # 2a <putchar>
    for (i = 0; i < (sizeof(uint64) * 2); i++, x <<= 4)
 22a:	0992                	slli	s3,s3,0x4
 22c:	397d                	addiw	s2,s2,-1
 22e:	fe0915e3          	bnez	s2,218 <vprintf+0x134>
                printptr(fd, va_arg(ap, uint64));
 232:	f8043a83          	ld	s5,-128(s0)
            state = 0;
 236:	4981                	li	s3,0
 238:	bf01                	j	148 <vprintf+0x64>
                s = va_arg(ap, char*);
 23a:	008a8993          	addi	s3,s5,8
 23e:	000ab903          	ld	s2,0(s5)
                if(s == 0)
 242:	02090063          	beqz	s2,262 <vprintf+0x17e>
                while(*s != 0){
 246:	00094503          	lbu	a0,0(s2)
 24a:	c529                	beqz	a0,294 <vprintf+0x1b0>
    putchar(c);
 24c:	00000097          	auipc	ra,0x0
 250:	dde080e7          	jalr	-546(ra) # 2a <putchar>
                    s++;
 254:	0905                	addi	s2,s2,1
                while(*s != 0){
 256:	00094503          	lbu	a0,0(s2)
 25a:	f96d                	bnez	a0,24c <vprintf+0x168>
                s = va_arg(ap, char*);
 25c:	8ace                	mv	s5,s3
            state = 0;
 25e:	4981                	li	s3,0
 260:	b5e5                	j	148 <vprintf+0x64>
                    s = "(null)";
 262:	00000917          	auipc	s2,0x0
 266:	0d690913          	addi	s2,s2,214 # 338 <printf+0x52>
                while(*s != 0){
 26a:	02800513          	li	a0,40
 26e:	bff9                	j	24c <vprintf+0x168>
                putc(fd, va_arg(ap, uint));
 270:	008a8913          	addi	s2,s5,8
    putchar(c);
 274:	000ac503          	lbu	a0,0(s5)
 278:	00000097          	auipc	ra,0x0
 27c:	db2080e7          	jalr	-590(ra) # 2a <putchar>
                putc(fd, va_arg(ap, uint));
 280:	8aca                	mv	s5,s2
            state = 0;
 282:	4981                	li	s3,0
}
 284:	b5d1                	j	148 <vprintf+0x64>
    putchar(c);
 286:	8552                	mv	a0,s4
 288:	00000097          	auipc	ra,0x0
 28c:	da2080e7          	jalr	-606(ra) # 2a <putchar>
            state = 0;
 290:	4981                	li	s3,0
}
 292:	bd5d                	j	148 <vprintf+0x64>
                s = va_arg(ap, char*);
 294:	8ace                	mv	s5,s3
            state = 0;
 296:	4981                	li	s3,0
 298:	bd45                	j	148 <vprintf+0x64>
        }
    }
}
 29a:	70e6                	ld	ra,120(sp)
 29c:	7446                	ld	s0,112(sp)
 29e:	74a6                	ld	s1,104(sp)
 2a0:	7906                	ld	s2,96(sp)
 2a2:	69e6                	ld	s3,88(sp)
 2a4:	6a46                	ld	s4,80(sp)
 2a6:	6aa6                	ld	s5,72(sp)
 2a8:	6b06                	ld	s6,64(sp)
 2aa:	7be2                	ld	s7,56(sp)
 2ac:	7c42                	ld	s8,48(sp)
 2ae:	7ca2                	ld	s9,40(sp)
 2b0:	7d02                	ld	s10,32(sp)
 2b2:	6de2                	ld	s11,24(sp)
 2b4:	6109                	addi	sp,sp,128
 2b6:	8082                	ret

00000000000002b8 <fprintf>:

void
fprintf(int fd, const char *fmt, ...)
{
 2b8:	715d                	addi	sp,sp,-80
 2ba:	ec06                	sd	ra,24(sp)
 2bc:	e822                	sd	s0,16(sp)
 2be:	1000                	addi	s0,sp,32
 2c0:	e010                	sd	a2,0(s0)
 2c2:	e414                	sd	a3,8(s0)
 2c4:	e818                	sd	a4,16(s0)
 2c6:	ec1c                	sd	a5,24(s0)
 2c8:	03043023          	sd	a6,32(s0)
 2cc:	03143423          	sd	a7,40(s0)
    va_list ap;

    va_start(ap, fmt);
 2d0:	fe843423          	sd	s0,-24(s0)
    vprintf(fd, fmt, ap);
 2d4:	8622                	mv	a2,s0
 2d6:	00000097          	auipc	ra,0x0
 2da:	e0e080e7          	jalr	-498(ra) # e4 <vprintf>
}
 2de:	60e2                	ld	ra,24(sp)
 2e0:	6442                	ld	s0,16(sp)
 2e2:	6161                	addi	sp,sp,80
 2e4:	8082                	ret

00000000000002e6 <printf>:

void
printf(const char *fmt, ...)
{
 2e6:	711d                	addi	sp,sp,-96
 2e8:	ec06                	sd	ra,24(sp)
 2ea:	e822                	sd	s0,16(sp)
 2ec:	1000                	addi	s0,sp,32
 2ee:	e40c                	sd	a1,8(s0)
 2f0:	e810                	sd	a2,16(s0)
 2f2:	ec14                	sd	a3,24(s0)
 2f4:	f018                	sd	a4,32(s0)
 2f6:	f41c                	sd	a5,40(s0)
 2f8:	03043823          	sd	a6,48(s0)
 2fc:	03143c23          	sd	a7,56(s0)
    va_list ap;

    va_start(ap, fmt);
 300:	00840613          	addi	a2,s0,8
 304:	fec43423          	sd	a2,-24(s0)
    vprintf(1, fmt, ap);
 308:	85aa                	mv	a1,a0
 30a:	4505                	li	a0,1
 30c:	00000097          	auipc	ra,0x0
 310:	dd8080e7          	jalr	-552(ra) # e4 <vprintf>
}
 314:	60e2                	ld	ra,24(sp)
 316:	6442                	ld	s0,16(sp)
 318:	6125                	addi	sp,sp,96
 31a:	8082                	ret
