
user/_init:     file format elf64-littleriscv


Disassembly of section .text:

0000000000000000 <main>:
#include "../kernel/fs/file.h"
#include "user.h"

char *argv[] = { "sh", 0 };

int main() {
   0:	1141                	addi	sp,sp,-16
   2:	e406                	sd	ra,8(sp)
   4:	e022                	sd	s0,0(sp)
   6:	0800                	addi	s0,sp,16
    if (open("/console", O_RDWR) < 0) {
   8:	4589                	li	a1,2
   a:	00000517          	auipc	a0,0x0
   e:	66e50513          	addi	a0,a0,1646 # 678 <max+0x18>
  12:	00000097          	auipc	ra,0x0
  16:	0d2080e7          	jalr	210(ra) # e4 <open>
  1a:	04054363          	bltz	a0,60 <main+0x60>
        mknod("/console", CONSOLE, 0);
        open("/console", O_RDWR);
    }
    dup(0); // stdout
  1e:	4501                	li	a0,0
  20:	00000097          	auipc	ra,0x0
  24:	0e4080e7          	jalr	228(ra) # 104 <dup>
    dup(0); // stderr
  28:	4501                	li	a0,0
  2a:	00000097          	auipc	ra,0x0
  2e:	0da080e7          	jalr	218(ra) # 104 <dup>
    char *s = "write: hello world!\n";
    printf("%s", s);
  32:	00000597          	auipc	a1,0x0
  36:	65658593          	addi	a1,a1,1622 # 688 <max+0x28>
  3a:	00000517          	auipc	a0,0x0
  3e:	66650513          	addi	a0,a0,1638 # 6a0 <max+0x40>
  42:	00000097          	auipc	ra,0x0
  46:	3ac080e7          	jalr	940(ra) # 3ee <printf>
    int pid = fork();
  4a:	00000097          	auipc	ra,0x0
  4e:	082080e7          	jalr	130(ra) # cc <fork>
    if (pid == 0) {
  52:	c91d                	beqz	a0,88 <main+0x88>
        exec("/sh\0", argv);
        exit(0);
    }
    for (;;) {
        wait(0);
  54:	4501                	li	a0,0
  56:	00000097          	auipc	ra,0x0
  5a:	086080e7          	jalr	134(ra) # dc <wait>
    for (;;) {
  5e:	bfdd                	j	54 <main+0x54>
        mknod("/console", CONSOLE, 0);
  60:	4601                	li	a2,0
  62:	4585                	li	a1,1
  64:	00000517          	auipc	a0,0x0
  68:	61450513          	addi	a0,a0,1556 # 678 <max+0x18>
  6c:	00000097          	auipc	ra,0x0
  70:	088080e7          	jalr	136(ra) # f4 <mknod>
        open("/console", O_RDWR);
  74:	4589                	li	a1,2
  76:	00000517          	auipc	a0,0x0
  7a:	60250513          	addi	a0,a0,1538 # 678 <max+0x18>
  7e:	00000097          	auipc	ra,0x0
  82:	066080e7          	jalr	102(ra) # e4 <open>
  86:	bf61                	j	1e <main+0x1e>
        exec("/sh\0", argv);
  88:	00000597          	auipc	a1,0x0
  8c:	65058593          	addi	a1,a1,1616 # 6d8 <argv>
  90:	00000517          	auipc	a0,0x0
  94:	62050513          	addi	a0,a0,1568 # 6b0 <max+0x50>
  98:	00000097          	auipc	ra,0x0
  9c:	01c080e7          	jalr	28(ra) # b4 <exec>
        exit(0);
  a0:	4501                	li	a0,0
  a2:	00000097          	auipc	ra,0x0
  a6:	032080e7          	jalr	50(ra) # d4 <exit>
  aa:	b76d                	j	54 <main+0x54>

00000000000000ac <putchar>:
# generated by usys.pl - do not edit
#include "kernel/trap/syscall.h"
.global putchar
putchar:
 li a7, SYS_putchar
  ac:	4885                	li	a7,1
 ecall
  ae:	00000073          	ecall
 ret
  b2:	8082                	ret

00000000000000b4 <exec>:
.global exec
exec:
 li a7, SYS_exec
  b4:	4889                	li	a7,2
 ecall
  b6:	00000073          	ecall
 ret
  ba:	8082                	ret

00000000000000bc <read>:
.global read
read:
 li a7, SYS_read
  bc:	4899                	li	a7,6
 ecall
  be:	00000073          	ecall
 ret
  c2:	8082                	ret

00000000000000c4 <write>:
.global write
write:
 li a7, SYS_write
  c4:	489d                	li	a7,7
 ecall
  c6:	00000073          	ecall
 ret
  ca:	8082                	ret

00000000000000cc <fork>:
.global fork
fork:
 li a7, SYS_fork
  cc:	4891                	li	a7,4
 ecall
  ce:	00000073          	ecall
 ret
  d2:	8082                	ret

00000000000000d4 <exit>:
.global exit
exit:
 li a7, SYS_exit
  d4:	488d                	li	a7,3
 ecall
  d6:	00000073          	ecall
 ret
  da:	8082                	ret

00000000000000dc <wait>:
.global wait
wait:
 li a7, SYS_wait
  dc:	4895                	li	a7,5
 ecall
  de:	00000073          	ecall
 ret
  e2:	8082                	ret

00000000000000e4 <open>:
.global open
open:
 li a7, SYS_open
  e4:	48a1                	li	a7,8
 ecall
  e6:	00000073          	ecall
 ret
  ea:	8082                	ret

00000000000000ec <mkdir>:
.global mkdir
mkdir:
 li a7, SYS_mkdir
  ec:	48a9                	li	a7,10
 ecall
  ee:	00000073          	ecall
 ret
  f2:	8082                	ret

00000000000000f4 <mknod>:
.global mknod
mknod:
 li a7, SYS_mknod
  f4:	48a5                	li	a7,9
 ecall
  f6:	00000073          	ecall
 ret
  fa:	8082                	ret

00000000000000fc <chdir>:
.global chdir
chdir:
 li a7, SYS_chdir
  fc:	48ad                	li	a7,11
 ecall
  fe:	00000073          	ecall
 ret
 102:	8082                	ret

0000000000000104 <dup>:
.global dup
dup:
 li a7, SYS_dup
 104:	48b1                	li	a7,12
 ecall
 106:	00000073          	ecall
 ret
 10a:	8082                	ret

000000000000010c <fstat>:
.global fstat
fstat:
 li a7, SYS_fstat
 10c:	48b5                	li	a7,13
 ecall
 10e:	00000073          	ecall
 ret
 112:	8082                	ret

0000000000000114 <putc>:
#include <stdarg.h>

static char digits[] = "0123456789ABCDEF";

static void
putc(int fd, char c) {
 114:	1101                	addi	sp,sp,-32
 116:	ec06                	sd	ra,24(sp)
 118:	e822                	sd	s0,16(sp)
 11a:	1000                	addi	s0,sp,32
 11c:	feb407a3          	sb	a1,-17(s0)
    write(0, &c, 1);
 120:	4605                	li	a2,1
 122:	fef40593          	addi	a1,s0,-17
 126:	4501                	li	a0,0
 128:	00000097          	auipc	ra,0x0
 12c:	f9c080e7          	jalr	-100(ra) # c4 <write>
}
 130:	60e2                	ld	ra,24(sp)
 132:	6442                	ld	s0,16(sp)
 134:	6105                	addi	sp,sp,32
 136:	8082                	ret

0000000000000138 <printint>:

static void
printint(int fd, int xx, int base, int sgn) {
 138:	7139                	addi	sp,sp,-64
 13a:	fc06                	sd	ra,56(sp)
 13c:	f822                	sd	s0,48(sp)
 13e:	f426                	sd	s1,40(sp)
 140:	f04a                	sd	s2,32(sp)
 142:	ec4e                	sd	s3,24(sp)
 144:	0080                	addi	s0,sp,64
 146:	84aa                	mv	s1,a0
    char buf[16];
    int i, neg;
    uint x;

    neg = 0;
    if (sgn && xx < 0) {
 148:	c299                	beqz	a3,14e <printint+0x16>
 14a:	0805c863          	bltz	a1,1da <printint+0xa2>
        neg = 1;
        x = -xx;
    } else {
        x = xx;
 14e:	2581                	sext.w	a1,a1
    neg = 0;
 150:	4881                	li	a7,0
 152:	fc040693          	addi	a3,s0,-64
    }

    i = 0;
 156:	4701                	li	a4,0
    do {
        buf[i++] = digits[x % base];
 158:	2601                	sext.w	a2,a2
 15a:	00000517          	auipc	a0,0x0
 15e:	56650513          	addi	a0,a0,1382 # 6c0 <digits>
 162:	883a                	mv	a6,a4
 164:	2705                	addiw	a4,a4,1
 166:	02c5f7bb          	remuw	a5,a1,a2
 16a:	1782                	slli	a5,a5,0x20
 16c:	9381                	srli	a5,a5,0x20
 16e:	97aa                	add	a5,a5,a0
 170:	0007c783          	lbu	a5,0(a5)
 174:	00f68023          	sb	a5,0(a3)
    } while ((x /= base) != 0);
 178:	0005879b          	sext.w	a5,a1
 17c:	02c5d5bb          	divuw	a1,a1,a2
 180:	0685                	addi	a3,a3,1
 182:	fec7f0e3          	bgeu	a5,a2,162 <printint+0x2a>
    if (neg)
 186:	00088b63          	beqz	a7,19c <printint+0x64>
        buf[i++] = '-';
 18a:	fd040793          	addi	a5,s0,-48
 18e:	973e                	add	a4,a4,a5
 190:	02d00793          	li	a5,45
 194:	fef70823          	sb	a5,-16(a4)
 198:	0028071b          	addiw	a4,a6,2

    while (--i >= 0)
 19c:	02e05863          	blez	a4,1cc <printint+0x94>
 1a0:	fc040793          	addi	a5,s0,-64
 1a4:	00e78933          	add	s2,a5,a4
 1a8:	fff78993          	addi	s3,a5,-1
 1ac:	99ba                	add	s3,s3,a4
 1ae:	377d                	addiw	a4,a4,-1
 1b0:	1702                	slli	a4,a4,0x20
 1b2:	9301                	srli	a4,a4,0x20
 1b4:	40e989b3          	sub	s3,s3,a4
        putc(fd, buf[i]);
 1b8:	fff94583          	lbu	a1,-1(s2)
 1bc:	8526                	mv	a0,s1
 1be:	00000097          	auipc	ra,0x0
 1c2:	f56080e7          	jalr	-170(ra) # 114 <putc>
    while (--i >= 0)
 1c6:	197d                	addi	s2,s2,-1
 1c8:	ff3918e3          	bne	s2,s3,1b8 <printint+0x80>
}
 1cc:	70e2                	ld	ra,56(sp)
 1ce:	7442                	ld	s0,48(sp)
 1d0:	74a2                	ld	s1,40(sp)
 1d2:	7902                	ld	s2,32(sp)
 1d4:	69e2                	ld	s3,24(sp)
 1d6:	6121                	addi	sp,sp,64
 1d8:	8082                	ret
        x = -xx;
 1da:	40b005bb          	negw	a1,a1
        neg = 1;
 1de:	4885                	li	a7,1
        x = -xx;
 1e0:	bf8d                	j	152 <printint+0x1a>

00000000000001e2 <vprintf>:
        putc(fd, digits[x >> (sizeof(uint64) * 8 - 4)]);
}

// Print to the given fd. Only understands %d, %x, %p, %s.
void
vprintf(int fd, const char *fmt, va_list ap) {
 1e2:	7119                	addi	sp,sp,-128
 1e4:	fc86                	sd	ra,120(sp)
 1e6:	f8a2                	sd	s0,112(sp)
 1e8:	f4a6                	sd	s1,104(sp)
 1ea:	f0ca                	sd	s2,96(sp)
 1ec:	ecce                	sd	s3,88(sp)
 1ee:	e8d2                	sd	s4,80(sp)
 1f0:	e4d6                	sd	s5,72(sp)
 1f2:	e0da                	sd	s6,64(sp)
 1f4:	fc5e                	sd	s7,56(sp)
 1f6:	f862                	sd	s8,48(sp)
 1f8:	f466                	sd	s9,40(sp)
 1fa:	f06a                	sd	s10,32(sp)
 1fc:	ec6e                	sd	s11,24(sp)
 1fe:	0100                	addi	s0,sp,128
    char *s;
    int c, i, state;

    state = 0;
    for (i = 0; fmt[i]; i++) {
 200:	0005c903          	lbu	s2,0(a1)
 204:	18090f63          	beqz	s2,3a2 <vprintf+0x1c0>
 208:	8aaa                	mv	s5,a0
 20a:	8b32                	mv	s6,a2
 20c:	00158493          	addi	s1,a1,1
    state = 0;
 210:	4981                	li	s3,0
            if (c == '%') {
                state = '%';
            } else {
                putc(fd, c);
            }
        } else if (state == '%') {
 212:	02500a13          	li	s4,37
            if (c == 'd') {
 216:	06400c13          	li	s8,100
                printint(fd, va_arg(ap, int), 10, 1);
            } else if (c == 'l') {
 21a:	06c00c93          	li	s9,108
                printint(fd, va_arg(ap, uint64), 10, 0);
            } else if (c == 'x') {
 21e:	07800d13          	li	s10,120
                printint(fd, va_arg(ap, int), 16, 0);
            } else if (c == 'p') {
 222:	07000d93          	li	s11,112
        putc(fd, digits[x >> (sizeof(uint64) * 8 - 4)]);
 226:	00000b97          	auipc	s7,0x0
 22a:	49ab8b93          	addi	s7,s7,1178 # 6c0 <digits>
 22e:	a839                	j	24c <vprintf+0x6a>
                putc(fd, c);
 230:	85ca                	mv	a1,s2
 232:	8556                	mv	a0,s5
 234:	00000097          	auipc	ra,0x0
 238:	ee0080e7          	jalr	-288(ra) # 114 <putc>
 23c:	a019                	j	242 <vprintf+0x60>
        } else if (state == '%') {
 23e:	01498f63          	beq	s3,s4,25c <vprintf+0x7a>
    for (i = 0; fmt[i]; i++) {
 242:	0485                	addi	s1,s1,1
 244:	fff4c903          	lbu	s2,-1(s1)
 248:	14090d63          	beqz	s2,3a2 <vprintf+0x1c0>
        c = fmt[i] & 0xff;
 24c:	0009079b          	sext.w	a5,s2
        if (state == 0) {
 250:	fe0997e3          	bnez	s3,23e <vprintf+0x5c>
            if (c == '%') {
 254:	fd479ee3          	bne	a5,s4,230 <vprintf+0x4e>
                state = '%';
 258:	89be                	mv	s3,a5
 25a:	b7e5                	j	242 <vprintf+0x60>
            if (c == 'd') {
 25c:	05878063          	beq	a5,s8,29c <vprintf+0xba>
            } else if (c == 'l') {
 260:	05978c63          	beq	a5,s9,2b8 <vprintf+0xd6>
            } else if (c == 'x') {
 264:	07a78863          	beq	a5,s10,2d4 <vprintf+0xf2>
            } else if (c == 'p') {
 268:	09b78463          	beq	a5,s11,2f0 <vprintf+0x10e>
                printptr(fd, va_arg(ap, uint64));
            } else if (c == 's') {
 26c:	07300713          	li	a4,115
 270:	0ce78663          	beq	a5,a4,33c <vprintf+0x15a>
                    s = "(null)";
                while (*s != 0) {
                    putc(fd, *s);
                    s++;
                }
            } else if (c == 'c') {
 274:	06300713          	li	a4,99
 278:	0ee78e63          	beq	a5,a4,374 <vprintf+0x192>
                putc(fd, va_arg(ap, uint));
            } else if (c == '%') {
 27c:	11478863          	beq	a5,s4,38c <vprintf+0x1aa>
                putc(fd, c);
            } else {
                // Unknown % sequence.  Print it to draw attention.
                putc(fd, '%');
 280:	85d2                	mv	a1,s4
 282:	8556                	mv	a0,s5
 284:	00000097          	auipc	ra,0x0
 288:	e90080e7          	jalr	-368(ra) # 114 <putc>
                putc(fd, c);
 28c:	85ca                	mv	a1,s2
 28e:	8556                	mv	a0,s5
 290:	00000097          	auipc	ra,0x0
 294:	e84080e7          	jalr	-380(ra) # 114 <putc>
            }
            state = 0;
 298:	4981                	li	s3,0
 29a:	b765                	j	242 <vprintf+0x60>
                printint(fd, va_arg(ap, int), 10, 1);
 29c:	008b0913          	addi	s2,s6,8
 2a0:	4685                	li	a3,1
 2a2:	4629                	li	a2,10
 2a4:	000b2583          	lw	a1,0(s6)
 2a8:	8556                	mv	a0,s5
 2aa:	00000097          	auipc	ra,0x0
 2ae:	e8e080e7          	jalr	-370(ra) # 138 <printint>
 2b2:	8b4a                	mv	s6,s2
            state = 0;
 2b4:	4981                	li	s3,0
 2b6:	b771                	j	242 <vprintf+0x60>
                printint(fd, va_arg(ap, uint64), 10, 0);
 2b8:	008b0913          	addi	s2,s6,8
 2bc:	4681                	li	a3,0
 2be:	4629                	li	a2,10
 2c0:	000b2583          	lw	a1,0(s6)
 2c4:	8556                	mv	a0,s5
 2c6:	00000097          	auipc	ra,0x0
 2ca:	e72080e7          	jalr	-398(ra) # 138 <printint>
 2ce:	8b4a                	mv	s6,s2
            state = 0;
 2d0:	4981                	li	s3,0
 2d2:	bf85                	j	242 <vprintf+0x60>
                printint(fd, va_arg(ap, int), 16, 0);
 2d4:	008b0913          	addi	s2,s6,8
 2d8:	4681                	li	a3,0
 2da:	4641                	li	a2,16
 2dc:	000b2583          	lw	a1,0(s6)
 2e0:	8556                	mv	a0,s5
 2e2:	00000097          	auipc	ra,0x0
 2e6:	e56080e7          	jalr	-426(ra) # 138 <printint>
 2ea:	8b4a                	mv	s6,s2
            state = 0;
 2ec:	4981                	li	s3,0
 2ee:	bf91                	j	242 <vprintf+0x60>
                printptr(fd, va_arg(ap, uint64));
 2f0:	008b0793          	addi	a5,s6,8
 2f4:	f8f43423          	sd	a5,-120(s0)
 2f8:	000b3983          	ld	s3,0(s6)
    putc(fd, '0');
 2fc:	03000593          	li	a1,48
 300:	8556                	mv	a0,s5
 302:	00000097          	auipc	ra,0x0
 306:	e12080e7          	jalr	-494(ra) # 114 <putc>
    putc(fd, 'x');
 30a:	85ea                	mv	a1,s10
 30c:	8556                	mv	a0,s5
 30e:	00000097          	auipc	ra,0x0
 312:	e06080e7          	jalr	-506(ra) # 114 <putc>
 316:	4941                	li	s2,16
        putc(fd, digits[x >> (sizeof(uint64) * 8 - 4)]);
 318:	03c9d793          	srli	a5,s3,0x3c
 31c:	97de                	add	a5,a5,s7
 31e:	0007c583          	lbu	a1,0(a5)
 322:	8556                	mv	a0,s5
 324:	00000097          	auipc	ra,0x0
 328:	df0080e7          	jalr	-528(ra) # 114 <putc>
    for (i = 0; i < (sizeof(uint64) * 2); i++, x <<= 4)
 32c:	0992                	slli	s3,s3,0x4
 32e:	397d                	addiw	s2,s2,-1
 330:	fe0914e3          	bnez	s2,318 <vprintf+0x136>
                printptr(fd, va_arg(ap, uint64));
 334:	f8843b03          	ld	s6,-120(s0)
            state = 0;
 338:	4981                	li	s3,0
 33a:	b721                	j	242 <vprintf+0x60>
                s = va_arg(ap, char*);
 33c:	008b0993          	addi	s3,s6,8
 340:	000b3903          	ld	s2,0(s6)
                if (s == 0)
 344:	02090163          	beqz	s2,366 <vprintf+0x184>
                while (*s != 0) {
 348:	00094583          	lbu	a1,0(s2)
 34c:	c9a1                	beqz	a1,39c <vprintf+0x1ba>
                    putc(fd, *s);
 34e:	8556                	mv	a0,s5
 350:	00000097          	auipc	ra,0x0
 354:	dc4080e7          	jalr	-572(ra) # 114 <putc>
                    s++;
 358:	0905                	addi	s2,s2,1
                while (*s != 0) {
 35a:	00094583          	lbu	a1,0(s2)
 35e:	f9e5                	bnez	a1,34e <vprintf+0x16c>
                s = va_arg(ap, char*);
 360:	8b4e                	mv	s6,s3
            state = 0;
 362:	4981                	li	s3,0
 364:	bdf9                	j	242 <vprintf+0x60>
                    s = "(null)";
 366:	00000917          	auipc	s2,0x0
 36a:	35290913          	addi	s2,s2,850 # 6b8 <max+0x58>
                while (*s != 0) {
 36e:	02800593          	li	a1,40
 372:	bff1                	j	34e <vprintf+0x16c>
                putc(fd, va_arg(ap, uint));
 374:	008b0913          	addi	s2,s6,8
 378:	000b4583          	lbu	a1,0(s6)
 37c:	8556                	mv	a0,s5
 37e:	00000097          	auipc	ra,0x0
 382:	d96080e7          	jalr	-618(ra) # 114 <putc>
 386:	8b4a                	mv	s6,s2
            state = 0;
 388:	4981                	li	s3,0
 38a:	bd65                	j	242 <vprintf+0x60>
                putc(fd, c);
 38c:	85d2                	mv	a1,s4
 38e:	8556                	mv	a0,s5
 390:	00000097          	auipc	ra,0x0
 394:	d84080e7          	jalr	-636(ra) # 114 <putc>
            state = 0;
 398:	4981                	li	s3,0
 39a:	b565                	j	242 <vprintf+0x60>
                s = va_arg(ap, char*);
 39c:	8b4e                	mv	s6,s3
            state = 0;
 39e:	4981                	li	s3,0
 3a0:	b54d                	j	242 <vprintf+0x60>
        }
    }
}
 3a2:	70e6                	ld	ra,120(sp)
 3a4:	7446                	ld	s0,112(sp)
 3a6:	74a6                	ld	s1,104(sp)
 3a8:	7906                	ld	s2,96(sp)
 3aa:	69e6                	ld	s3,88(sp)
 3ac:	6a46                	ld	s4,80(sp)
 3ae:	6aa6                	ld	s5,72(sp)
 3b0:	6b06                	ld	s6,64(sp)
 3b2:	7be2                	ld	s7,56(sp)
 3b4:	7c42                	ld	s8,48(sp)
 3b6:	7ca2                	ld	s9,40(sp)
 3b8:	7d02                	ld	s10,32(sp)
 3ba:	6de2                	ld	s11,24(sp)
 3bc:	6109                	addi	sp,sp,128
 3be:	8082                	ret

00000000000003c0 <fprintf>:

void
fprintf(int fd, const char *fmt, ...) {
 3c0:	715d                	addi	sp,sp,-80
 3c2:	ec06                	sd	ra,24(sp)
 3c4:	e822                	sd	s0,16(sp)
 3c6:	1000                	addi	s0,sp,32
 3c8:	e010                	sd	a2,0(s0)
 3ca:	e414                	sd	a3,8(s0)
 3cc:	e818                	sd	a4,16(s0)
 3ce:	ec1c                	sd	a5,24(s0)
 3d0:	03043023          	sd	a6,32(s0)
 3d4:	03143423          	sd	a7,40(s0)
    va_list ap;

    va_start(ap, fmt);
 3d8:	fe843423          	sd	s0,-24(s0)
    vprintf(fd, fmt, ap);
 3dc:	8622                	mv	a2,s0
 3de:	00000097          	auipc	ra,0x0
 3e2:	e04080e7          	jalr	-508(ra) # 1e2 <vprintf>
}
 3e6:	60e2                	ld	ra,24(sp)
 3e8:	6442                	ld	s0,16(sp)
 3ea:	6161                	addi	sp,sp,80
 3ec:	8082                	ret

00000000000003ee <printf>:

void
printf(const char *fmt, ...) {
 3ee:	711d                	addi	sp,sp,-96
 3f0:	ec06                	sd	ra,24(sp)
 3f2:	e822                	sd	s0,16(sp)
 3f4:	1000                	addi	s0,sp,32
 3f6:	e40c                	sd	a1,8(s0)
 3f8:	e810                	sd	a2,16(s0)
 3fa:	ec14                	sd	a3,24(s0)
 3fc:	f018                	sd	a4,32(s0)
 3fe:	f41c                	sd	a5,40(s0)
 400:	03043823          	sd	a6,48(s0)
 404:	03143c23          	sd	a7,56(s0)
    va_list ap;

    va_start(ap, fmt);
 408:	00840613          	addi	a2,s0,8
 40c:	fec43423          	sd	a2,-24(s0)
    vprintf(1, fmt, ap);
 410:	85aa                	mv	a1,a0
 412:	4505                	li	a0,1
 414:	00000097          	auipc	ra,0x0
 418:	dce080e7          	jalr	-562(ra) # 1e2 <vprintf>
}
 41c:	60e2                	ld	ra,24(sp)
 41e:	6442                	ld	s0,16(sp)
 420:	6125                	addi	sp,sp,96
 422:	8082                	ret

0000000000000424 <strncpy>:
#include "../kernel/types.h"
#include "../kernel/fs/fcntl.h"
#include "user.h"
//string utils
char * strncpy(char *s, const char *t, int n) {
 424:	1141                	addi	sp,sp,-16
 426:	e422                	sd	s0,8(sp)
 428:	0800                	addi	s0,sp,16
    char *os;

    os = s;
    while (n-- > 0 && (*s++ = *t++) != 0);
 42a:	872a                	mv	a4,a0
 42c:	8832                	mv	a6,a2
 42e:	367d                	addiw	a2,a2,-1
 430:	01005963          	blez	a6,442 <strncpy+0x1e>
 434:	0705                	addi	a4,a4,1
 436:	0005c783          	lbu	a5,0(a1)
 43a:	fef70fa3          	sb	a5,-1(a4)
 43e:	0585                	addi	a1,a1,1
 440:	f7f5                	bnez	a5,42c <strncpy+0x8>
    while (n-- > 0)
 442:	00c05d63          	blez	a2,45c <strncpy+0x38>
 446:	86ba                	mv	a3,a4
        *s++ = 0;
 448:	0685                	addi	a3,a3,1
 44a:	fe068fa3          	sb	zero,-1(a3)
    while (n-- > 0)
 44e:	fff6c793          	not	a5,a3
 452:	9fb9                	addw	a5,a5,a4
 454:	010787bb          	addw	a5,a5,a6
 458:	fef048e3          	bgtz	a5,448 <strncpy+0x24>
    return os;
}
 45c:	6422                	ld	s0,8(sp)
 45e:	0141                	addi	sp,sp,16
 460:	8082                	ret

0000000000000462 <strcpy>:

char* strcpy(char* s, const char* t)
{
 462:	1141                	addi	sp,sp,-16
 464:	e422                	sd	s0,8(sp)
 466:	0800                	addi	s0,sp,16
    char* os;
    os = s;
    while ((*s++ = *t++) != 0)
 468:	87aa                	mv	a5,a0
 46a:	0585                	addi	a1,a1,1
 46c:	0785                	addi	a5,a5,1
 46e:	fff5c703          	lbu	a4,-1(a1)
 472:	fee78fa3          	sb	a4,-1(a5)
 476:	fb75                	bnez	a4,46a <strcpy+0x8>
        ;
    return os;
}
 478:	6422                	ld	s0,8(sp)
 47a:	0141                	addi	sp,sp,16
 47c:	8082                	ret

000000000000047e <strcmp>:

int strcmp(const char* p, const char* q)
{
 47e:	1141                	addi	sp,sp,-16
 480:	e422                	sd	s0,8(sp)
 482:	0800                	addi	s0,sp,16
    while (*p && *p == *q)
 484:	00054783          	lbu	a5,0(a0)
 488:	cb91                	beqz	a5,49c <strcmp+0x1e>
 48a:	0005c703          	lbu	a4,0(a1)
 48e:	00f71763          	bne	a4,a5,49c <strcmp+0x1e>
        p++, q++;
 492:	0505                	addi	a0,a0,1
 494:	0585                	addi	a1,a1,1
    while (*p && *p == *q)
 496:	00054783          	lbu	a5,0(a0)
 49a:	fbe5                	bnez	a5,48a <strcmp+0xc>
    return (uchar)*p - (uchar)*q;
 49c:	0005c503          	lbu	a0,0(a1)
}
 4a0:	40a7853b          	subw	a0,a5,a0
 4a4:	6422                	ld	s0,8(sp)
 4a6:	0141                	addi	sp,sp,16
 4a8:	8082                	ret

00000000000004aa <strlen>:

uint strlen(const char *s) {
 4aa:	1141                	addi	sp,sp,-16
 4ac:	e422                	sd	s0,8(sp)
 4ae:	0800                	addi	s0,sp,16
    int n;
    for (n = 0; s[n]; n++);
 4b0:	00054783          	lbu	a5,0(a0)
 4b4:	cf91                	beqz	a5,4d0 <strlen+0x26>
 4b6:	0505                	addi	a0,a0,1
 4b8:	87aa                	mv	a5,a0
 4ba:	4685                	li	a3,1
 4bc:	9e89                	subw	a3,a3,a0
 4be:	00f6853b          	addw	a0,a3,a5
 4c2:	0785                	addi	a5,a5,1
 4c4:	fff7c703          	lbu	a4,-1(a5)
 4c8:	fb7d                	bnez	a4,4be <strlen+0x14>
    return n;
}
 4ca:	6422                	ld	s0,8(sp)
 4cc:	0141                	addi	sp,sp,16
 4ce:	8082                	ret
    for (n = 0; s[n]; n++);
 4d0:	4501                	li	a0,0
 4d2:	bfe5                	j	4ca <strlen+0x20>

00000000000004d4 <strchr>:

char* strchr(const char* s, char c)
{
 4d4:	1141                	addi	sp,sp,-16
 4d6:	e422                	sd	s0,8(sp)
 4d8:	0800                	addi	s0,sp,16
    for (; *s; s++)
 4da:	00054783          	lbu	a5,0(a0)
 4de:	cb99                	beqz	a5,4f4 <strchr+0x20>
        if (*s == c)
 4e0:	00f58763          	beq	a1,a5,4ee <strchr+0x1a>
    for (; *s; s++)
 4e4:	0505                	addi	a0,a0,1
 4e6:	00054783          	lbu	a5,0(a0)
 4ea:	fbfd                	bnez	a5,4e0 <strchr+0xc>
            return (char*)s;
    return 0;
 4ec:	4501                	li	a0,0
}
 4ee:	6422                	ld	s0,8(sp)
 4f0:	0141                	addi	sp,sp,16
 4f2:	8082                	ret
    return 0;
 4f4:	4501                	li	a0,0
 4f6:	bfe5                	j	4ee <strchr+0x1a>

00000000000004f8 <stat>:
//     return buf;
// }

int
stat(const char *s, struct stat *st)
{
 4f8:	1101                	addi	sp,sp,-32
 4fa:	ec06                	sd	ra,24(sp)
 4fc:	e822                	sd	s0,16(sp)
 4fe:	e426                	sd	s1,8(sp)
 500:	1000                	addi	s0,sp,32
 502:	84ae                	mv	s1,a1
    int fd;
    int r;

    fd = open(s, O_RDONLY);
 504:	4581                	li	a1,0
 506:	00000097          	auipc	ra,0x0
 50a:	bde080e7          	jalr	-1058(ra) # e4 <open>
    if(fd < 0)
 50e:	00054c63          	bltz	a0,526 <stat+0x2e>
        return -1;
    r = fstat(fd, st);
 512:	85a6                	mv	a1,s1
 514:	00000097          	auipc	ra,0x0
 518:	bf8080e7          	jalr	-1032(ra) # 10c <fstat>
//    close(fd);
    return r;
}
 51c:	60e2                	ld	ra,24(sp)
 51e:	6442                	ld	s0,16(sp)
 520:	64a2                	ld	s1,8(sp)
 522:	6105                	addi	sp,sp,32
 524:	8082                	ret
        return -1;
 526:	557d                	li	a0,-1
 528:	bfd5                	j	51c <stat+0x24>

000000000000052a <atoi>:

int atoi(const char* s)
{
 52a:	1141                	addi	sp,sp,-16
 52c:	e422                	sd	s0,8(sp)
 52e:	0800                	addi	s0,sp,16
    int n;

    n = 0;
    while ('0' <= *s && *s <= '9')
 530:	00054603          	lbu	a2,0(a0)
 534:	fd06079b          	addiw	a5,a2,-48
 538:	0ff7f793          	andi	a5,a5,255
 53c:	4725                	li	a4,9
 53e:	02f76963          	bltu	a4,a5,570 <atoi+0x46>
 542:	86aa                	mv	a3,a0
    n = 0;
 544:	4501                	li	a0,0
    while ('0' <= *s && *s <= '9')
 546:	45a5                	li	a1,9
        n = n * 10 + *s++ - '0';
 548:	0685                	addi	a3,a3,1
 54a:	0025179b          	slliw	a5,a0,0x2
 54e:	9fa9                	addw	a5,a5,a0
 550:	0017979b          	slliw	a5,a5,0x1
 554:	9fb1                	addw	a5,a5,a2
 556:	fd07851b          	addiw	a0,a5,-48
    while ('0' <= *s && *s <= '9')
 55a:	0006c603          	lbu	a2,0(a3)
 55e:	fd06071b          	addiw	a4,a2,-48
 562:	0ff77713          	andi	a4,a4,255
 566:	fee5f1e3          	bgeu	a1,a4,548 <atoi+0x1e>
    return n;
}
 56a:	6422                	ld	s0,8(sp)
 56c:	0141                	addi	sp,sp,16
 56e:	8082                	ret
    n = 0;
 570:	4501                	li	a0,0
 572:	bfe5                	j	56a <atoi+0x40>

0000000000000574 <memset>:

//memory utils
 void* memset(void* dst, int c, uint n)
 {
 574:	1141                	addi	sp,sp,-16
 576:	e422                	sd	s0,8(sp)
 578:	0800                	addi	s0,sp,16
     char* cdst = (char*)dst;
     int i;
     for (i = 0; i < n; i++) {
 57a:	ce09                	beqz	a2,594 <memset+0x20>
 57c:	87aa                	mv	a5,a0
 57e:	fff6071b          	addiw	a4,a2,-1
 582:	1702                	slli	a4,a4,0x20
 584:	9301                	srli	a4,a4,0x20
 586:	0705                	addi	a4,a4,1
 588:	972a                	add	a4,a4,a0
         cdst[i] = c;
 58a:	00b78023          	sb	a1,0(a5)
     for (i = 0; i < n; i++) {
 58e:	0785                	addi	a5,a5,1
 590:	fee79de3          	bne	a5,a4,58a <memset+0x16>
     }
     return dst;
 }
 594:	6422                	ld	s0,8(sp)
 596:	0141                	addi	sp,sp,16
 598:	8082                	ret

000000000000059a <memmove>:

 void* memmove(void* vdst, const void* vsrc, int n)
 {
 59a:	1141                	addi	sp,sp,-16
 59c:	e422                	sd	s0,8(sp)
 59e:	0800                	addi	s0,sp,16
     char* dst;
     const char* src;

     dst = vdst;
     src = vsrc;
     if (src > dst) {
 5a0:	02b57663          	bgeu	a0,a1,5cc <memmove+0x32>
         while (n-- > 0)
 5a4:	02c05163          	blez	a2,5c6 <memmove+0x2c>
 5a8:	fff6079b          	addiw	a5,a2,-1
 5ac:	1782                	slli	a5,a5,0x20
 5ae:	9381                	srli	a5,a5,0x20
 5b0:	0785                	addi	a5,a5,1
 5b2:	97aa                	add	a5,a5,a0
     dst = vdst;
 5b4:	872a                	mv	a4,a0
             *dst++ = *src++;
 5b6:	0585                	addi	a1,a1,1
 5b8:	0705                	addi	a4,a4,1
 5ba:	fff5c683          	lbu	a3,-1(a1)
 5be:	fed70fa3          	sb	a3,-1(a4)
         while (n-- > 0)
 5c2:	fee79ae3          	bne	a5,a4,5b6 <memmove+0x1c>
         src += n;
         while (n-- > 0)
             *--dst = *--src;
     }
     return vdst;
 }
 5c6:	6422                	ld	s0,8(sp)
 5c8:	0141                	addi	sp,sp,16
 5ca:	8082                	ret
         dst += n;
 5cc:	00c50733          	add	a4,a0,a2
         src += n;
 5d0:	95b2                	add	a1,a1,a2
         while (n-- > 0)
 5d2:	fec05ae3          	blez	a2,5c6 <memmove+0x2c>
 5d6:	fff6079b          	addiw	a5,a2,-1
 5da:	1782                	slli	a5,a5,0x20
 5dc:	9381                	srli	a5,a5,0x20
 5de:	fff7c793          	not	a5,a5
 5e2:	97ba                	add	a5,a5,a4
             *--dst = *--src;
 5e4:	15fd                	addi	a1,a1,-1
 5e6:	177d                	addi	a4,a4,-1
 5e8:	0005c683          	lbu	a3,0(a1)
 5ec:	00d70023          	sb	a3,0(a4)
         while (n-- > 0)
 5f0:	fee79ae3          	bne	a5,a4,5e4 <memmove+0x4a>
 5f4:	bfc9                	j	5c6 <memmove+0x2c>

00000000000005f6 <memcmp>:

int memcmp(const void* s1, const void* s2, uint n)
{
 5f6:	1141                	addi	sp,sp,-16
 5f8:	e422                	sd	s0,8(sp)
 5fa:	0800                	addi	s0,sp,16
    const char *p1 = s1, *p2 = s2;
    while (n-- > 0) {
 5fc:	ca05                	beqz	a2,62c <memcmp+0x36>
 5fe:	fff6069b          	addiw	a3,a2,-1
 602:	1682                	slli	a3,a3,0x20
 604:	9281                	srli	a3,a3,0x20
 606:	0685                	addi	a3,a3,1
 608:	96aa                	add	a3,a3,a0
        if (*p1 != *p2) {
 60a:	00054783          	lbu	a5,0(a0)
 60e:	0005c703          	lbu	a4,0(a1)
 612:	00e79863          	bne	a5,a4,622 <memcmp+0x2c>
            return *p1 - *p2;
        }
        p1++;
 616:	0505                	addi	a0,a0,1
        p2++;
 618:	0585                	addi	a1,a1,1
    while (n-- > 0) {
 61a:	fed518e3          	bne	a0,a3,60a <memcmp+0x14>
    }
    return 0;
 61e:	4501                	li	a0,0
 620:	a019                	j	626 <memcmp+0x30>
            return *p1 - *p2;
 622:	40e7853b          	subw	a0,a5,a4
}
 626:	6422                	ld	s0,8(sp)
 628:	0141                	addi	sp,sp,16
 62a:	8082                	ret
    return 0;
 62c:	4501                	li	a0,0
 62e:	bfe5                	j	626 <memcmp+0x30>

0000000000000630 <memcpy>:

void* memcpy(void* dst, const void* src, uint n)
{
 630:	1141                	addi	sp,sp,-16
 632:	e406                	sd	ra,8(sp)
 634:	e022                	sd	s0,0(sp)
 636:	0800                	addi	s0,sp,16
    return memmove(dst, src, n);
 638:	00000097          	auipc	ra,0x0
 63c:	f62080e7          	jalr	-158(ra) # 59a <memmove>
}
 640:	60a2                	ld	ra,8(sp)
 642:	6402                	ld	s0,0(sp)
 644:	0141                	addi	sp,sp,16
 646:	8082                	ret

0000000000000648 <min>:

//math utils
int min(int a, int b)
{
 648:	1141                	addi	sp,sp,-16
 64a:	e422                	sd	s0,8(sp)
 64c:	0800                	addi	s0,sp,16
    return a < b ? a : b;
 64e:	87ae                	mv	a5,a1
 650:	00b55363          	bge	a0,a1,656 <min+0xe>
 654:	87aa                	mv	a5,a0
}
 656:	0007851b          	sext.w	a0,a5
 65a:	6422                	ld	s0,8(sp)
 65c:	0141                	addi	sp,sp,16
 65e:	8082                	ret

0000000000000660 <max>:
int max(int a, int b)
{
 660:	1141                	addi	sp,sp,-16
 662:	e422                	sd	s0,8(sp)
 664:	0800                	addi	s0,sp,16
    return a > b ? a : b;
 666:	87ae                	mv	a5,a1
 668:	00a5d363          	bge	a1,a0,66e <max+0xe>
 66c:	87aa                	mv	a5,a0
}
 66e:	0007851b          	sext.w	a0,a5
 672:	6422                	ld	s0,8(sp)
 674:	0141                	addi	sp,sp,16
 676:	8082                	ret
