#!/usr/bin/perl -w

# Generate usys.S, the stubs for syscalls.

print "# generated by usys.pl - do not edit\n";

print "#include \"kernel/trap/syscall.h\"\n";

sub entry {
    my $name = shift;
    print ".global $name\n";
    print "${name}:\n";
    print " li a7, SYS_${name}\n";
    print " ecall\n";
    print " ret\n";
}

entry("putchar");
entry("exec");
entry("read");
entry("write");
entry("fork");
entry("exit");
entry("wait");
entry("open");
entry("mkdir");
entry("mknod");
entry("chdir");
entry("dup");
entry("fstat");


